frollous/frollo-android-sdk

changelog.md
src/androidTest/kotlin/us/frollo/frollosdk/aggregation/AggregationTest.kt
src/androidTest/res/raw/accounts_valid.json
src/main/kotlin/us/frollo/frollosdk/database/Converters.kt
src/main/kotlin/us/frollo/frollosdk/mapping/AggregationMapping.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/aggregation/accounts/AccountFeature.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/aggregation/accounts/AccountFeatureDetail.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/aggregation/accounts/AccountFeatureSubType.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/aggregation/accounts/AccountFeatureType.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/aggregation/providers/AggregatorType.kt
src/sharedTest/kotlin/us/frollo/frollosdk/model/TestDataAccount.kt
src/test/kotlin/us/frollo/frollosdk/database/ConvertersTest.kt

- Add coming_soon and outage to Provider status
- Change Account Feature models ID field type to Enum from String

SDK-470, SDK-452 : Provider Availability Status and Update Account Feature Models

---

src/androidTest/kotlin/us/frollo/frollosdk/BaseAndroidTest.kt
src/androidTest/kotlin/us/frollo/frollosdk/FrolloSDKAndroidUnitTest.kt
src/androidTest/kotlin/us/frollo/frollosdk/contacts/ContactsTest.kt
src/main/kotlin/us/frollo/frollosdk/FrolloSDK.kt
src/main/kotlin/us/frollo/frollosdk/contacts/Contacts.kt
src/main/kotlin/us/frollo/frollosdk/contacts/ContactsRx.kt
src/main/kotlin/us/frollo/frollosdk/extensions/APIExtension.kt
src/main/kotlin/us/frollo/frollosdk/extensions/ModelExtension.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/contacts/ContactPaginationInfo.kt
src/main/kotlin/us/frollo/frollosdk/network/NetworkService.kt
src/main/kotlin/us/frollo/frollosdk/network/api/ContactsAPI.kt
src/test/kotlin/us/frollo/frollosdk/extensions/ModelExtensionTest.kt

WA-979
WA-984
WA-983
WA-980
WA-981
WA-982

Contacts methods & tests

---

changelog.md
extras.md
src/androidTest/kotlin/us/frollo/frollosdk/payments/PaymentsTest.kt
src/androidTest/res/raw/payment_verify_bpay_invalid.json
src/androidTest/res/raw/payment_verify_bpay_valid.json
src/main/kotlin/us/frollo/frollosdk/model/api/payments/VerifyBPayRequest.kt
src/main/kotlin/us/frollo/frollosdk/model/api/payments/VerifyBPayResponse.kt
src/main/kotlin/us/frollo/frollosdk/network/api/PaymentsAPI.kt
src/main/kotlin/us/frollo/frollosdk/payments/Payments.kt

API Doc - https://beta.developer.frollo.com.au/api/client-api/payments/verify-bpay

SDK-553 : Verify BPay

---

README.md
build.gradle
changelog.md
src/androidTest/kotlin/us/frollo/frollosdk/aggregation/AggregationTest.kt
src/androidTest/kotlin/us/frollo/frollosdk/error/APIErrorTest.kt
src/androidTest/res/raw/error_payment_character_limit_exceeded.json
src/androidTest/res/raw/error_payment_invalid_amount.json
src/androidTest/res/raw/payment_limits.json
src/main/kotlin/us/frollo/frollosdk/aggregation/Aggregation.kt
src/main/kotlin/us/frollo/frollosdk/model/api/payments/PayAnyoneResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/api/payments/PaymentBPayResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/api/payments/PaymentPayIdResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/api/payments/PaymentTransferResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/api/shared/APIErrorCode.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/payments/PaymentLimit.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/payments/PaymentLimitPeriod.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/payments/PaymentLimitType.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/payments/PaymentMode.kt
src/main/kotlin/us/frollo/frollosdk/network/api/AggregationAPI.kt

https://frollo.atlassian.net/wiki/spaces/PROD/pages/2594570603/Payment+Limits#Get-Payment-Limits
SDK-649 : Payments - Add payment_type to responses
SDK-651 : Payments Limit APIs
SDK-656 : Add new error codes for payments

Payments Limit APIs, New Error codes

---

changelog.md
src/androidTest/kotlin/us/frollo/frollosdk/aggregation/AggregationTest.kt
src/androidTest/res/raw/accounts_valid.json
src/main/kotlin/us/frollo/frollosdk/database/Converters.kt
src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
src/main/kotlin/us/frollo/frollosdk/mapping/AggregationMapping.kt
src/main/kotlin/us/frollo/frollosdk/model/api/aggregation/accounts/AccountResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/api/user/payid/UserPayIdAccountResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/aggregation/accounts/Account.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/contacts/PayIDType.kt
src/main/kotlin/us/frollo/frollosdk/network/NetworkHelper.kt
src/sharedTest/kotlin/us/frollo/frollosdk/model/TestDataAccount.kt
src/test/kotlin/us/frollo/frollosdk/database/ConvertersTest.kt

https://next.stoplight.io/frollo/frollo-developer-portal/version%2F2.15/client-api.v2.oas3.yml?view=%2Faggregation%2Flist-accounts

SDK-658 : Account - Associated PayIDs

---

changelog.md
src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
src/main/kotlin/us/frollo/frollosdk/mapping/AggregationMapping.kt
src/main/kotlin/us/frollo/frollosdk/model/api/aggregation/providers/ProviderResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/aggregation/providers/Provider.kt
src/sharedTest/kotlin/us/frollo/frollosdk/model/TestDataProvider.kt

[WA-2321](https://frollo.atlassian.net/browse/WA-2321): Provider API changes to support joint accounts linking
[API Docs](https://next.stoplight.io/frollo/frollo-developer-portal/version%2F2.15/client-api.v2.oas3.yml?view=%2Faggregation%2Fget-provider)
* Has the code been properly covered with unit & android tests? …

WA-2321: Provider API changes to support joint accounts linking

---

changelog.md
src/androidTest/kotlin/us/frollo/frollosdk/managedproducts/ManagedProductsTest.kt
src/androidTest/res/raw/managed_products_response.json
src/main/kotlin/us/frollo/frollosdk/model/coredata/managedproduct/ManagedProduct.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/managedproduct/ProductFeature.kt

[SDK-685](https://frollo.atlassian.net/browse/SDK-685)
[API Docs](https://next.stoplight.io/frollo/frollo-developer-portal/version%2F2.15/client-api.v2.oas3.yml?view=%2Fmanaged-products%2Flist-available-products)
* Has the code been properly covered with unit & android tests? :white_check_mark:
* Have the full test suite …

SDK-685 : Add features array to Managed Product API response

---

changelog.md
src/main/kotlin/us/frollo/frollosdk/model/api/user/UserRegisterRequest.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/user/UserStatus.kt
src/main/kotlin/us/frollo/frollosdk/user/UserManagement.kt

[SDK-692](https://frollo.atlassian.net/browse/SDK-692) : Additional user statuses - Failed, Created, Invited
[SDK-690](https://frollo.atlassian.net/browse/SDK-690) : Optional first name during user registration
[API Docs](https://beta.developer.frollo.com.au/api/client-api/user/get-user-details)
* Has the code been properly covered …

SDK-692 &SDK-690 : Register API changes and User Status changes

---

build.gradle
changelog.md
src/androidTest/kotlin/us/frollo/frollosdk/payments/PaymentsTest.kt
src/main/kotlin/us/frollo/frollosdk/payments/Payments.kt

[WA-2739](https://frollo.atlassian.net/browse/WA-2739) …

Adding override_method field in Payanyone request

---

src/main/kotlin/us/frollo/frollosdk/base/Resource.kt
src/main/kotlin/us/frollo/frollosdk/extensions/NetworkExtensions.kt

[Add a link to the ticket](https://frollo.atlassian.net/browse/<TICKET_NUMBER>): A Description of the problem and what needs to be achieved.
[Add a link to the any API Docs/Confluence Page (if applicable)](https://next.stoplight.io/frollo/<path>)
What's the technical solution?
Did you have to make any architectural decision that might be worth sharing?
* Is the destination branch correct & intended?
* Is the code synced to latest (if applicable)?
* Has the SDK example app build passed locally?
* Is the correct JIRA ticket referenced?
* Is the correct API docs/Confluence Page referenced?
* Have all the AC's in the ticket …

FROLLO-6912 add status code to success response

---

build.gradle
changelog.md
src/androidTest/kotlin/us/frollo/frollosdk/kyc/KYCTest.kt
src/androidTest/kotlin/us/frollo/frollosdk/user/UserManagementTest.kt
src/androidTest/res/raw/user_details_complete.json
src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
src/main/kotlin/us/frollo/frollosdk/kyc/KYC.kt
src/main/kotlin/us/frollo/frollosdk/mapping/UserMapping.kt
src/main/kotlin/us/frollo/frollosdk/model/api/kyc/KycRequest.kt
src/main/kotlin/us/frollo/frollosdk/model/api/user/UserRegisterRequest.kt
src/main/kotlin/us/frollo/frollosdk/model/api/user/UserResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/api/user/UserUpdateRequest.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/kyc/UserKyc.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/user/User.kt
src/main/kotlin/us/frollo/frollosdk/network/NetworkHelper.kt
src/sharedTest/kotlin/us/frollo/frollosdk/model/TestDataKyc.kt
src/sharedTest/kotlin/us/frollo/frollosdk/model/TestDataUser.kt

[SDK-707](https://frollo.atlassian.net/browse/SDK-707)
[API Docs - Register User](https://frollo.stoplight.io/docs/frollo-api/branches/develop/b3A6MjQwOTE0MzE-register-user)
[API Docs - Update User](https://frollo.stoplight.io/docs/frollo-api/branches/develop/b3A6MjQwOTE0Mzc-update-user-details)
[API Docs - Get User](https://frollo.stoplight.io/docs/frollo-api/branches/develop/b3A6MjQwOTE0MzY-get-user-details)
[API Docs - Create KYC](https://frollo.stoplight.io/docs/frollo-api/branches/develop/b3A6MjQwOTI2NTU-create-and-verify-kyc)
* Is …

SDK-707 kyc & user details API changes

---

changelog.md
src/androidTest/kotlin/us/frollo/frollosdk/servicestatus/ServiceStatusManagementTest.kt
src/main/kotlin/us/frollo/frollosdk/network/NetworkHelper.kt
src/main/kotlin/us/frollo/frollosdk/network/api/ServiceStatusAPI.kt
src/main/kotlin/us/frollo/frollosdk/servicestatus/ServiceStatusManagement.kt

[SDK-702](https://frollo.atlassian.net/browse/SDK-702) …

SDK-702 : Status API - X-Host Header

---

src/androidTest/kotlin/us/frollo/frollosdk/contacts/ContactsTest.kt
src/main/kotlin/us/frollo/frollosdk/contacts/Contacts.kt

[SDK-703](https://frollo.atlassian.net/browse/SDK-703)
* Have the full test suite (unit & android tests) passed locally?:white_check_mark: 
* Has the changelog.md, packages.md, overview.md, extras.md been updated?:white_check_mark: 
* Has the …

SDK-703 : Contacts - Remove name parameter for create/update

---

changelog.md
src/androidTest/kotlin/us/frollo/frollosdk/aggregation/AggregationTest.kt
src/androidTest/kotlin/us/frollo/frollosdk/database/dao/CDRConfigurationDaoTest.kt
src/androidTest/res/raw/cdr_configuration.json
src/main/kotlin/us/frollo/frollosdk/aggregation/Aggregation.kt
src/main/kotlin/us/frollo/frollosdk/database/Converters.kt
src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
src/main/kotlin/us/frollo/frollosdk/database/dao/CDRConfigurationDao.kt
src/main/kotlin/us/frollo/frollosdk/mapping/AggregationMapping.kt
src/main/kotlin/us/frollo/frollosdk/model/api/cdr/CDRConfigurationResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/CDRConfiguration.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/CDRModel.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/CDRParty.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/CDRPartyType.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/CDRPolicy.kt
src/main/kotlin/us/frollo/frollosdk/network/api/CdrAPI.kt
src/sharedTest/kotlin/us/frollo/frollosdk/model/TestDataConsent.kt
src/test/kotlin/us/frollo/frollosdk/database/ConvertersTest.kt

[SDK-709](https://frollo.atlassian.net/browse/SDK-709)
[API Docs](https://frollo.stoplight.io/docs/frollo-api/branches/develop/b3A6MzcxNTQ5MDk-cdr-config)
* Has the …

SDK-709 update cdr config api

---

changelog.md
src/androidTest/kotlin/us/frollo/frollosdk/logging/LogTest.kt
src/androidTest/kotlin/us/frollo/frollosdk/logging/NetworkLoggerTest.kt
src/main/kotlin/us/frollo/frollosdk/FrolloSDK.kt
src/main/kotlin/us/frollo/frollosdk/core/FrolloSDKConfiguration.kt
src/main/kotlin/us/frollo/frollosdk/logging/Log.kt
src/main/kotlin/us/frollo/frollosdk/logging/NetworkLogger.kt
src/main/kotlin/us/frollo/frollosdk/logging/NetworkLoggingProvider.kt
src/sharedTest/kotlin/us/frollo/frollosdk/core/TestSDKConfig.kt

[SDK-706](https://frollo.atlassian.net/browse/SDK-706) …

SDK-706 : Refactor Logging

---

README.md
build.gradle
changelog.md
src/main/kotlin/us/frollo/frollosdk/model/coredata/aggregation/providers/AggregatorType.kt

[WA-3147](https://frollo.atlassian.net/browse/WA-3147)
* Have the full test suite (unit & android tests) passed locally?:white_check_mark: 
* Has the changelog.md, packages.md, overview.md, extras.md been updated?:white_check_mark: 
* Has the …

WA-3147 : Add new aggregator type data_action

---

src/androidTest/kotlin/us/frollo/frollosdk/aggregation/AggregationTest.kt
src/main/kotlin/us/frollo/frollosdk/aggregation/Aggregation.kt
src/main/kotlin/us/frollo/frollosdk/network/api/AggregationAPI.kt

[WA-3281 ](https://frollo.atlassian.net/browse/WA-3281)
[API Doc](https://frollo.stoplight.io/docs/frollo-api/branches/version%2F2.15/b3A6MjQwOTI1MzU-delete-account)
* Have you followed proper naming conventions in the …

WA-3281 Delete manual account

---

src/androidTest/kotlin/us/frollo/frollosdk/aggregation/AggregationTest.kt
src/main/kotlin/us/frollo/frollosdk/aggregation/Aggregation.kt
src/main/kotlin/us/frollo/frollosdk/network/api/AggregationAPI.kt

[WA-3280](https://frollo.atlassian.net/browse/WA-3280)
[API Docs](https://frollo.stoplight.io/docs/frollo-api/b3A6MjQwOTE0NDg-update-account-details)
* Have the full test suite (unit & android tests) passed locally?:white_check_mark: 
* Has …

WA-3280 : Update Manual Account

---

changelog.md
src/androidTest/kotlin/us/frollo/frollosdk/aggregation/AggregationTest.kt
src/androidTest/kotlin/us/frollo/frollosdk/payments/PaymentsTest.kt
src/androidTest/res/raw/payment_verify_pay_anyone_valid.json
src/androidTest/res/raw/payment_verify_payid_response.json
src/androidTest/res/raw/transaction_id_194630.json
src/androidTest/res/raw/transactions_page_1.json
src/main/kotlin/us/frollo/frollosdk/database/Converters.kt
src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
src/main/kotlin/us/frollo/frollosdk/mapping/AggregationMapping.kt
src/main/kotlin/us/frollo/frollosdk/model/api/aggregation/transactions/TransactionResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/api/payments/VerifyPayAnyoneResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/api/payments/VerifyPayIdResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/aggregation/transactions/Transaction.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/payments/NPPServiceIdType.kt
src/main/kotlin/us/frollo/frollosdk/network/NetworkHelper.kt
src/sharedTest/kotlin/us/frollo/frollosdk/model/TestDataTransaction.kt
src/test/kotlin/us/frollo/frollosdk/database/ConvertersTest.kt

https://frollo.atlassian.net/browse/WA-3291
https://frollo.stoplight.io/docs/frollo-api/branches/develop/b3A6MjQwOTE0NDk-list-transactions
https://frollo.stoplight.io/docs/frollo-api/branches/develop/b3A6MjQwOTI2NDQ-verify-pay-anyone
https://frollo.stoplight.io/docs/frollo-api/branches/develop/b3A6MjQwOTI2NDU-verify-pay-id
* Has …

WA-3291 : Osko changes

---

build.gradle

[WA-3496](https://frollo.atlassian.net/browse/WA-3496)

WA-3469 - Remove support for Android 6 & 7

---

build.gradle
changelog.md
src/androidTest/res/raw/financial_passport_response.json
src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPAssetsBreakdownAccounts.kt
src/main/kotlin/us/frollo/frollosdk/model/api/affordability/FPLiabilitiesBreakdownAccounts.kt

[WA-3500](https://frollo.atlassian.net/browse/WA-3500)
* Have the full …

WA-3500 Updated frequency fields in assets & liabilities breakdown

---

changelog.md
src/androidTest/kotlin/us/frollo/frollosdk/aggregation/AggregationTest.kt
src/main/kotlin/us/frollo/frollosdk/aggregation/Aggregation.kt
src/main/kotlin/us/frollo/frollosdk/network/api/AggregationAPI.kt

https://frollo.atlassian.net/browse/WA-3761 …

WA-3761: Quick Sync API

---

changelog.md
src/androidTest/kotlin/us/frollo/frollosdk/extensions/NetworkExtensionTest.kt
src/main/kotlin/us/frollo/frollosdk/FrolloSDK.kt
src/main/kotlin/us/frollo/frollosdk/authentication/AuthenticationStatus.kt
src/main/kotlin/us/frollo/frollosdk/authentication/OAuth2Authentication.kt
src/main/kotlin/us/frollo/frollosdk/core/Constants.kt
src/main/kotlin/us/frollo/frollosdk/error/OAuth2Error.kt
src/main/kotlin/us/frollo/frollosdk/extensions/NetworkExtensions.kt
src/main/kotlin/us/frollo/frollosdk/user/UserManagement.kt

https://frollo.atlassian.net/browse/WA-3840
* Has the code been properly covered with unit & android tests? :white_check_mark:
* Have the full test suite (unit & android tests) passed locally? :white_check_mark:
* Has the changelog.md, packages.md, overview.md, extras.md been updated? :white_check_mark: …

WA-3840 : Handle 410 Error

---

src/androidTest/kotlin/us/frollo/frollosdk/aggregation/AggregationTest.kt
src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
src/main/kotlin/us/frollo/frollosdk/mapping/AggregationMapping.kt
src/main/kotlin/us/frollo/frollosdk/model/api/cdr/CDRConfigurationResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/CDRConfiguration.kt
src/sharedTest/kotlin/us/frollo/frollosdk/model/TestDataConsent.kt

https://frollo.atlassian.net/browse/WA-3884 …

WA-3884 : Add Initial Sync Window Weeks to CDR Configuration

---

src/main/kotlin/us/frollo/frollosdk/model/coredata/bills/BillFrequency.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/budgets/BudgetFrequency.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/goals/GoalFrequency.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/reports/TransactionReportPeriod.kt

* Is the destination branch correct & intended? ✅
* Is the code synced to latest (if applicable)? ✅
* Has the SDK example app build passed locally? ✅
* Is the correct JIRA ticket referenced? ✅
* Is the correct API docs/Confluence Page referenced? ✅
* Have all the AC's in the ticket passed? ✅
* Have you followed proper naming conventions in the code? ✅
* Has the code been properly covered with unit & android tests? ✅
* Have the full test suite (unit & android tests) passed locally? ✅
* Has the changelog.md, packages.md, overview.md, extras.md been updated? ✅
* Has the dokka task passed? ✅
* Have you committed database schema changes (if applicable)? ✅

WA-3885: add bimonthly frequency

---

changelog.md
extras.md
src/androidTest/kotlin/us/frollo/frollosdk/database/dao/MessageDaoTest.kt
src/androidTest/kotlin/us/frollo/frollosdk/messages/MessagesTest.kt
src/androidTest/res/raw/messages_unread_page1.json
src/androidTest/res/raw/messages_unread_page2.json
src/androidTest/res/raw/messages_update_in_bulk.json
src/androidTest/res/raw/messages_update_read.json
src/main/kotlin/us/frollo/frollosdk/FrolloSDK.kt
src/main/kotlin/us/frollo/frollosdk/database/dao/MessageDao.kt
src/main/kotlin/us/frollo/frollosdk/messages/Messages.kt
src/main/kotlin/us/frollo/frollosdk/model/api/messages/MessageBulkUpdateRequest.kt
src/main/kotlin/us/frollo/frollosdk/network/api/MessagesAPI.kt

https://frollo.atlassian.net/browse/WA-3779
https://frollo.atlassian.net/browse/WA-3781
https://frollo.atlassian.net/wiki/spaces/DEV/pages/2976940091/Messages+API+Enhancements
* Have the full test suite (unit & android tests) passed …

Messages API Changes

---

src/androidTest/kotlin/us/frollo/frollosdk/messages/MessagesTest.kt
src/main/kotlin/us/frollo/frollosdk/extensions/APIExtension.kt
src/main/kotlin/us/frollo/frollosdk/messages/Messages.kt
src/main/kotlin/us/frollo/frollosdk/network/api/MessagesAPI.kt

https://frollo.atlassian.net/browse/WA-3780 …

WA-3780: Delete Messages API

---

.github/dependabot.yml

* Is the destination branch correct & intended? ✅
* Is the code synced to latest (if applicable)? ✅
* Has the SDK example app build passed locally? ✅
* Is the correct JIRA ticket referenced? ✅
* Is the correct API docs/Confluence Page referenced? ✅
* Have all the AC's in the ticket passed? ✅
* Have you followed proper naming conventions in the code? ✅
* Has the code been properly covered with unit & android tests? ✅
* Have the full test suite (unit & android tests) passed locally? ✅
* Has the changelog.md, packages.md, overview.md, extras.md been updated? ✅
* Has the dokka task passed? ✅
* Have you committed database schema changes (if applicable)? ✅

WA-3855: configure dependabot for android sdk

---

src/androidTest/kotlin/us/frollo/frollosdk/appconfiguration/AppConfigurationTest.kt
src/main/kotlin/us/frollo/frollosdk/appconfiguration/AppConfiguration.kt
src/main/kotlin/us/frollo/frollosdk/network/NetworkService.kt

WA-3740
Changes in network service to cater to build retrofit calls to all types.
* Has the code been properly covered with unit & android …

WA-3740 - Update Network service changes , App Config changes

---

changelog.md
src/androidTest/kotlin/us/frollo/frollosdk/consents/ConsentTest.kt
src/androidTest/kotlin/us/frollo/frollosdk/database/dao/DisclosureConsentDaoTest.kt
src/androidTest/res/raw/disclosure_consent_page_1.json
src/androidTest/res/raw/disclosure_consent_page_2.json
src/androidTest/res/raw/disclosure_consent_page_3.json
src/main/kotlin/us/frollo/frollosdk/consents/Consents.kt
src/main/kotlin/us/frollo/frollosdk/consents/ConsentsRx.kt
src/main/kotlin/us/frollo/frollosdk/database/Converters.kt
src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
src/main/kotlin/us/frollo/frollosdk/database/dao/DisclosureConsentDao.kt
src/main/kotlin/us/frollo/frollosdk/extensions/APIExtension.kt
src/main/kotlin/us/frollo/frollosdk/extensions/ModelExtension.kt
src/main/kotlin/us/frollo/frollosdk/mapping/ConsentsMapping.kt
src/sharedTest/kotlin/us/frollo/frollosdk/model/TestDataConsent.kt
src/test/kotlin/us/frollo/frollosdk/database/ConvertersTest.kt
src/test/kotlin/us/frollo/frollosdk/extensions/ModelExtensionTest.kt
src/test/kotlin/us/frollo/frollosdk/mapping/ConsentsMappingTest.kt

[WA-4000](https://frollo.atlassian.net/browse/WA-4000)
[API doc](https://frollo.stoplight.io/docs/frollo-api/b8dbb6df2728d-list-disclosure-consents)
* Has …

WA-4000 Disclosure consents API implementation PART 2

---

src/androidTest/kotlin/us/frollo/frollosdk/aggregation/AggregationTest.kt
src/androidTest/kotlin/us/frollo/frollosdk/consents/ConsentTest.kt
src/androidTest/kotlin/us/frollo/frollosdk/database/dao/DisclosureConsentDaoTest.kt
src/main/kotlin/us/frollo/frollosdk/aggregation/Aggregation.kt
src/main/kotlin/us/frollo/frollosdk/extensions/APIExtension.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/aggregation/transactions/ExportTransactionField.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/aggregation/transactions/ExportTransactionFilter.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/aggregation/transactions/ExportTransactionType.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/ExternalParty.kt
src/main/kotlin/us/frollo/frollosdk/network/api/AggregationAPI.kt
src/test/kotlin/us/frollo/frollosdk/database/ConvertersTest.kt

[WA-4079](https://frollo.atlassian.net/browse/WA-4079)
[API Docs](https://frollo.stoplight.io/docs/frollo-api/branches/develop/ef7477dcbe4b7-export-transactions)
* Has …

WA-4079 : Export Transactions

---

src/androidTest/kotlin/us/frollo/frollosdk/consents/ConsentTest.kt
src/androidTest/res/raw/cdr_configuration.json
src/androidTest/res/raw/disclosure_consent_page_2.json
src/androidTest/res/raw/disclosure_consent_page_3.json
src/androidTest/res/raw/external_party_id_353.json
src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
src/main/kotlin/us/frollo/frollosdk/mapping/ConsentsMapping.kt
src/main/kotlin/us/frollo/frollosdk/model/api/cdr/CDRConfigurationResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/CDRConfiguration.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/CDRParty.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/CDRPermission.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/SharingDuration.kt
src/sharedTest/kotlin/us/frollo/frollosdk/model/TestDataConsent.kt
src/test/kotlin/us/frollo/frollosdk/database/ConvertersTest.kt

https://frollo.atlassian.net/browse/WA-4155
[Confluence Page](https://frollo.atlassian.net/wiki/spaces/DEV/pages/3043688542/CDR+Config+Parties+Enhancements)
* Has the …

WA-4155 : CDR Config updates

---

src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
src/main/kotlin/us/frollo/frollosdk/mapping/ConsentsMapping.kt
src/main/kotlin/us/frollo/frollosdk/model/api/cdr/ExternalPartyResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/ExternalParty.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/ExternalPartyCompany.kt
src/sharedTest/kotlin/us/frollo/frollosdk/model/TestDataConsent.kt
src/test/kotlin/us/frollo/frollosdk/database/ConvertersTest.kt

[WA-4120](https://frollo.atlassian.net/browse/WA-4120)
* Has the code been properly covered with unit & android tests?
* Have the full test suite (unit & android …

WA-4120 External party & disclosure_consent table changes

---

src/main/kotlin/us/frollo/frollosdk/aggregation/Aggregation.kt
src/main/kotlin/us/frollo/frollosdk/extensions/APIExtension.kt

[WA-4116](https://frollo.atlassian.net/browse/WA-4116)
* Has the code been properly covered with unit & android tests?NA
* Have the full test suite (unit & …

WA-4116 Add query params to get similar transactions API

---

src/androidTest/kotlin/us/frollo/frollosdk/consents/ConsentTest.kt
src/androidTest/res/raw/cdr_configuration.json
src/androidTest/res/raw/disclosure_consent_page_2.json
src/androidTest/res/raw/disclosure_consent_page_3.json
src/androidTest/res/raw/external_party_id_353.json
src/main/kotlin/us/frollo/frollosdk/database/SDKDatabase.kt
src/main/kotlin/us/frollo/frollosdk/mapping/ConsentsMapping.kt
src/main/kotlin/us/frollo/frollosdk/model/api/cdr/CDRConfigurationResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/CDRConfiguration.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/cdr/SharingDuration.kt
src/sharedTest/kotlin/us/frollo/frollosdk/model/TestDataConsent.kt
src/test/kotlin/us/frollo/frollosdk/database/ConvertersTest.kt

https://frollo.atlassian.net/browse/WA-4164
* Have the full test suite (unit & android tests) passed locally?:white_check_mark: 
* Has the changelog.md, packages.md, overview.md, extras.md been updated?:white_check_mark:  …

WA-4164 : Reverting CDR Config Changes as they are removed from API v2.21

---

build.gradle

[WA-4218](https://frollo.atlassian.net/browse/WA-4218)
* Has the code been properly covered with unit & android tests?NA
* Have the full test suite (unit & android …

WA-4218 Update Android min support version to Pie 9.0

---

src/androidTest/kotlin/us/frollo/frollosdk/affordability/AffordabilityTest.kt
src/androidTest/res/raw/networth_response.json
src/main/kotlin/us/frollo/frollosdk/affordability/Affordability.kt
src/main/kotlin/us/frollo/frollosdk/extensions/APIExtension.kt
src/main/kotlin/us/frollo/frollosdk/model/api/affordability/NetworthAssetsLiabilities.kt
src/main/kotlin/us/frollo/frollosdk/model/api/affordability/NetworthResponse.kt
src/main/kotlin/us/frollo/frollosdk/model/api/affordability/NetworthSummary.kt
src/main/kotlin/us/frollo/frollosdk/model/api/affordability/NetworthSummaryAggregatorTotals.kt
src/main/kotlin/us/frollo/frollosdk/model/api/affordability/NetworthSummaryTotals.kt
src/main/kotlin/us/frollo/frollosdk/network/api/AffordabilityAPI.kt

[WA-4328](https://frollo.atlassian.net/browse/WA-4238)
* Is the destination branch correct & intended? :white_check_mark: 
* Is the code synced to latest (if applicable)? :white_check_mark: 
* Has the SDK example app build passed locally? :white_check_mark: 
* Is the correct JIRA ticket referenced? :white_check_mark: 
* Is the correct API docs/Confluence Page referenced? :white_check_mark: 
* Have all the AC's in the ticket passed? :white_check_mark: 
* Have you followed proper naming conventions in the code? :white_check_mark: 
* Has the code been properly covered with unit & android tests? :white_check_mark: 
* Have the …

WA-4328 Networth API updates

---

src/androidTest/kotlin/us/frollo/frollosdk/reports/ReportsTest.kt
src/main/kotlin/us/frollo/frollosdk/extensions/APIExtension.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/reports/ReportsBaseType.kt
src/main/kotlin/us/frollo/frollosdk/reports/Reports.kt

[WA-4301 ](https://frollo.atlassian.net/browse/WA-4301)
* Have the full …

 WA-4301 Added baseType query param for all the Reports APIs

---

src/androidTest/kotlin/us/frollo/frollosdk/affordability/AffordabilityTest.kt
src/main/kotlin/us/frollo/frollosdk/affordability/Affordability.kt
src/main/kotlin/us/frollo/frollosdk/core/TypeAliases.kt

WA-4332
* Has the code been properly covered with unit & android tests? :white_check_mark:
* Have the full test suite (unit & android tests) passed locally? …

WA-4332 Handle 202 response status code.

---

src/main/kotlin/us/frollo/frollosdk/bills/Bills.kt
src/main/kotlin/us/frollo/frollosdk/model/api/bills/BillPaymentUpdateRequest.kt

[WA-4564](https://frollo.atlassian.net/browse/WA-4564)
[WA-4598](https://frollo.atlassian.net/browse/WA-4598)
[WA-4599](https://frollo.atlassian.net/browse/WA-4599)
[WA-4564]: https://frollo.atlassian.net/browse/WA-4564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WA-4598]: https://frollo.atlassian.net/browse/WA-4598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WA-4599]: https://frollo.atlassian.net/browse/WA-4599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WA-4564 Add `transaction_id` in BillPayment Request as per latest API doc

---

src/main/kotlin/us/frollo/frollosdk/appconfiguration/AppConfiguration.kt
src/main/kotlin/us/frollo/frollosdk/appconfiguration/AppConfigurationSuspended.kt
src/main/kotlin/us/frollo/frollosdk/database/dao/CompanyConfigDao.kt
src/main/kotlin/us/frollo/frollosdk/database/dao/FeatureConfigDao.kt
src/main/kotlin/us/frollo/frollosdk/database/dao/LinkConfigDao.kt
src/main/kotlin/us/frollo/frollosdk/model/coredata/aggregation/transactions/TransactionStatus.kt
src/main/kotlin/us/frollo/frollosdk/network/api/AppConfigurationAPI.kt

As per story: 
https://frollo.atlassian.net/browse/WA-4830
* SDK support for loading AppConfiguration with co-routines
* SDK support for loading FeatureConfig with co-routines
* SDK support for loading LinkConfig with co-routines
Pure SDK support in Kotlin, no screenshots at this time

WA-4830: Enable/Disable cashflow feature based on flag from app config

---

src/main/kotlin/us/frollo/frollosdk/database/dao/UserDao.kt
src/main/kotlin/us/frollo/frollosdk/user/UserManagement.kt

https://frollo.atlassian.net/browse/WA-4847
* Added fetching an existing user from Local DB using co-routines
* Pure SDK change, screenshots to be supplied in Frollo App

WA-4847: Frollo app to pass these values to Typeform survey
